kind: Service
apiVersion: v1
metadata:
  name: authorizer-service
  namespace: default
spec:
  selector:
    app: authorizer

  type: NodePort

  ports:
    - name: http
      # nodePort a utilizar
      nodePort: 30000
      # porta do service
      port: 8080
      # port do container
      targetPort: 8080