version: '3'

services:
  authorizer-mysql:
    image: mysql:5.7
    container_name: authorizer-mysql
    networks:
      - turingq-keycloak-net        
    volumes:
      - turingq-keycloak-mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  authorizer:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: turingq-authorizer-dev
    networks:
      - turingq-keycloak-net    
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: authorizer-mysql
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - authorizer-mysql

  authorizer-config:
    image: quay.io/adorsys/keycloak-config-cli:latest-15.0.2
    container_name: turingq-authorizer-config-dev
    networks:
      - turingq-keycloak-net
    restart: always
    environment:
      KEYCLOAK_URL: http://turingq-authorizer-dev:8080/auth
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_SSLVERIFY: "false"
      IMPORT_PATH: /config
    volumes:
      - ./config/turingq.json:/config/turingq.json
    depends_on:
      - authorizer
    
networks:
  turingq-keycloak-net:
    driver: bridge

volumes:
  turingq-keycloak-mysql_data:
    driver: local