apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type:  NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: frontend