apiVersion: apps/v1
kind: Deployment

metadata:
  name: authorizer-postgres
  namespace: default
spec:
  selector:
    matchLabels:
      app: authorizer-postgres
  template:
    metadata:
      labels:
        app: authorizer-postgres
    spec:  
      containers: 
        - image: postgres:11
          name: authorizer-postgres  
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authorizer-postgres-secret
                  key: password      
            - name: POSTGRES_DB
              value: keycloak                            
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: auth-db-pg                
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: authorizer-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: authorizer-postgres-storage
          persistentVolumeClaim:
            claimName: authorizer-postgres-postgres-pvc
