# apiVersion: v1
# kind: Secret
# metadata:
#   name: authorizer-config-secret
#   namespace: default
# type: Opaque
# data:
#   KEYCLOAK_USER: 'a2V5Y2xvYWstYWRtaW4='
#   KEYCLOAK_PASSWORD: 'a2V5Y2xvYWstYWRtaW4='