# apiVersion: v1
# kind: Secret
# metadata:
#   name: core-secret
#   namespace: default
# type: Opaque

# data:
#   # A chave usada pelo Adonis para encriptação 
#   APP_KEY: 'YWRvbmlzanMtYXBwa2V5LWNoYW5nZS1tZQ=='
#   PG_USER: 'cG9zdGdyZXM='
#   PG_PASSWORD: 'cG9zdGdyZXM='
#   # "secret" do cliente dentro do Keycloak.
#   # Em produção recomenda-se gerar um novo secret na interface
#   # do Keycloak antes de utilizá-lo aqui. Caso você gere um
#   # novo secret no Keycloak, deve convertê-lo em base64 antes e colocá-lo aqui.
#   KEYCLOAK_CLIENT_SECRET: 'Y29yZS1zZWNyZXQtY2hhbmdlLW1l'