kind: Service
apiVersion: v1
metadata:
  name: message-broker-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 15672
      targetPort: 15672
  selector:
    app: message-broker